spring.application.name=url-shorten-v1
server.port=8083

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/url_shortner_spring
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#flyway migrations
spring.flyway.enabled=true

#verify schema and act on table
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

#Redis config
#spring.data.redis.host=${SPRING_DATA_REDIS_HOST} #:localhost
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000

#tomcat server
server.tomcat.threads.max=500
server.tomcat.accept-count=1000
server.tomcat.max-connections=8192
server.tomcat.connection-timeout=5s

#hickri cp
spring.datasource.hikari.maximum-pool-size=50
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.initialization-fail-timeout=0